language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: fmCq8CPbD30Qz4pZHQbnZsbywJM2zRT2mkLI6+X+Hh04j7zBZC2cwQXaYrl4X8HIQjyBbhN3OVl0faKHqRwtsSxb9wCELNBciHt45QnlFa8CWLDSvc7JfsTxwvmpYh/eeoKh7o4QY2BTjz1WI7Eyh/PfhyaQ6WlBQIAEuww2qVZki+JMupgbgL7YhBVo07On31dBsDxdJv2/T4ZlKQubR8jpAk/FyHqDBlhWMZEha8R8PGjOvoNlvhsktEdHILIzmckxJeb4++svi0MtFpr6U3hBpJuW1bs62RyVIFm5rJ7Oja89B/pFo5TiopM8KT+VbFMbIL0KA3qDHDe4HiboBe2MtodJCve2eQbnhlFMBcJl18BV+jambBh5Y5aG1ySJSRTfqyOjCu0/Zs1fvR2ppst2dOmRRwG7jRxRvO3X1ZlUa3F3LEHnGYv2jfnGPNeoKAAi/xyFzhVSIYVSD84PloVRbGUPaJ/0Hy28rQF7uvAI2xpu6lqG192j3lOylkfzlid5tk8kY9OZyOS2Zt+WjDQ0FA6TZakOPO7VXvKlgBndE1hVxEntyDtrQVBzl44952JVjQzsoyzrBCs9j+21vR7J3rbrYeZBnxL8drjAAr4H+IFTVYtSy6XPMkhkjOFxuyWMtweTgxo41qtR7n+HzpNMXmcHBrhyvKCHrcGHKWU=
  file:
    - 'match-casing.js'
    - 'match-casing.min.js'
  on:
    tags: true
